### ISSUE TITLE
Closers viewing accounts they're tagged to.

### ISSUE THREAD

**Issue by bethanygenninger** [NRGCSDevelopers/Genesis-Public#12]
So right now, the only people who can view appointments/conference calls in Genesis are the people who create the request but we need the updated this so that the people who the accounts are assigned to can also view the accounts in their dashboard.  Ex: Karen sets up a conference call that Lacey assigns to Scott but Scott cannot view the conference call details in Genesis, only Karen can view the call since she was the one who created it.  This limits the closers from being able to read Karen's notes on the call prior to having the conference call with the customer.

**Comment by LLNowicki** [comment]
As an additional note assigned to = Name appears in inside rep, outside rep or closer fields.

**Comment by bgarrison25** [comment]
This issue was moved to NRGCSDevelopers/genesis#56
