### ISSUE TITLE
Missing Information and appointment reschedules

### ISSUE THREAD

**Issue by LLNowicki** [NRGCSDevelopers/Genesis-Public#13]
When a salesperson reschedules an appointment valuable information is missing off of the email kicker including the contact and their phone number which is becoming more and more of an issue. I have no idea from this if its the same person and phone number or what- then I have to chase the salesperson down to ask, hunt down old notes in ACT! etc can we either add in the contact form, or save the information from the first appointment entry when they resched?

![image](https://user-images.githubusercontent.com/36669045/40306901-6db01666-5cce-11e8-847d-6e1dc7165b15.png)

**Comment by bgarrison25** [comment]
This issue was moved to NRGCSDevelopers/genesis#57
