### ISSUE TITLE
Outside/Closing rep fields

### ISSUE THREAD

**Issue by LLNowicki** [NRGCSDevelopers/Genesis-Public#6]
I would like to be able to select a blank for outside/closing rep fields.  Sometimes a meeting gets rescheduled to a conference call and an outside rep no longer applies. I currently lack the ability to remove them.

**Comment by bgarrison25** [comment]
Ask for the WORLD why don't ya ;)

**Comment by LLNowicki** [comment]
Could you get it for me? XD

Lacey Nowicki
NRG
Sales Support Team
T: 716.906.5263
Email: Lacey.Nowicki@nrg.com<mailto:Lacey.Nowicki@nrg.com>
