### ISSUE TITLE
Regular Appointment Dashboard Enhancement Request

### ISSUE THREAD

**Issue by LLNowicki** [NRGCSDevelopers/Genesis-Public#7]
![image](https://user-images.githubusercontent.com/36669045/38427367-0bbe6ad0-3987-11e8-996e-f0eeaf2c204f.png)

On the NON admin appt dashboard reps should be able to filter their stuff too. Filters I think they would find useful: Date, type, and status.

**Comment by LLNowicki** [comment]
Filters are visible but not functional on first test.

**Comment by bgarrison25** [comment]
This issue was moved to NRGCSDevelopers/genesis#55
